### PR TITLE
feat: create single command for srl migrate

### LINKED ISSUE #160: Create single command that migrates STEPmod repository into SRL
Given the STEPMod directory (`stepmod/`), produce the following:

2 commands:
* `stepmod-srl-migrate-docs --stepmod-data-dir stepmod/data --srl-docs-dir documents`
* `stepmod-srl-migrate-schemas --stepmod-data-dir stepmod/data --srl-schemas-dir schemas`

## Resulting output

* `documents/`: containing:
    * `documents/resources/{document-name}` and `documents/modules/{document-name}`:
        * `stepmod2mn` document migration output (Metanorma `*.adoc` files)
* `schemas/`: containing:
    * `schemas/{schema-name}/`
        * `stepmod2mn` migrated EXPRESS-G diagrams (`*.svg` files)
        * `stepmod-utils` "Annotated EXPRESS" output (`*_annotated.exp` files => renamed to `*.exp`)
        * `stepmod-utils` "EXPRESS schema changes" output (`*.yaml` files) (https://github.com/metanorma/stepmod-utils/issues/146)

## Create Metanorma documents: `stepmod-srl-migrate-docs`

Prerequisites:
* Make sure `stepmod2mn.jar` is available, if not, download it.

Steps:
* create the `srl-docs-dir` directory (i.e. `documents/`)
* run `stepmod2mn.jar` to migrate documents into the `srl-docs-dir` directory

## Migrate EXPRESS schemas: `stepmod-srl-migrate-schemas`

Prerequisites:
* Make sure `stepmod2mn.jar` is available, if not, download it. 

Steps:
* create the `srl-schemas-dir` directory (i.e. `schemas/`)
* run the functionality of `stepmod-annotate-all` to create `*_annotated.exp` files (but name them `*.exp` without the `_annotated` suffix), place them in `{srl-schemas-dir}/{schema-name}/*.exp`
* run the functionality of `stepmod-extract-changes` to create `*.yaml` files for schema change information, place them in `{srl-schemas-dir}/{schema-name}/*.yaml`
* run `stepmod2mn` to migrate the EXPRESS-G files (the `*.svg` files), place them in `{srl-schemas-dir}/{schema-name}/*.svg`

## One step command: `stepmod-srl-migrate`

* Run `stepmod-srl-migrate-docs`
* Run `stepmod-srl-migrate-schemas`

### PR DESCRIPTION
**Pull request by HassanAkbar**
Create single command that migrates STEPmod repository into SRL 

closes #160

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse I have a question related to `stepmod-srl-migrate-docs`,

- In the` documents/` folder do we only need the `.adoc` files? If yes then in `stepmod2mn` I didn't find any option to only generate the `adoc` files so, should I remove other files after the generation of documents?

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
> * In the` documents/` folder do we only need the `.adoc` files? If yes then in `stepmod2mn` I didn't find any option to only generate the `adoc` files so, should I remove other files after the generation of documents?

What files are remaining?

**Comment by HassanAkbar** [comment]
@ronaldtse I've tested this on the `iso-10303-stepmod-wg12` repo and the following files are also present inside the `documents/{resources or modules}/` directory
- `.svg`
- `collection.sh`
- `collection.yml`
- `html_attachments.sh`
- `schemas.yaml`

**Comment by TRThurman** [comment]
What command initiates the process?Which file contains the list of documents to include in the SRL?TomSent from my iPhoneOn Sep 28, 2023, at 1:36 AM, HassanAkbar ***@***.***> wrote:﻿
@ronaldtse I've tested this on the iso-10303-stepmod-wg12 repo and the following files are also present inside the documents/{resources or modules}/ directory

.svg
collection.sh
collection.yml
html_attachments.sh
schemas.yaml

**Comment by HassanAkbar** [comment]
@TRThurman the `documents` folder is generated by the given command `java -Xss5m -jar target/stepmod2mn-1.17.jar <Input-folder> --output documents`

**Comment by TRThurman** [comment]
ok, so we will just tailor the input directory content before calling the command.
Simple enough.

**Comment by ronaldtse** [comment]
> @ronaldtse I've tested this on the `iso-10303-stepmod-wg12` repo and the following files are also present inside the `documents/{resources or modules}/` directory
> 
> * `.svg`
When you say `.svg` did you mean `*.svg`? Or an SVG with no name?

> * `collection.sh`
Shouldn't be there.

> * `collection.yml`
Shouldn't be there.

> * `html_attachments.sh`
Shouldn't be there.

> * `schemas.yaml`
Shouldn't be there.

Ping @Intelligent2013 on why these files are created.

**Comment by Intelligent2013** [comment]
`collection.sh` calls `html_attachments.sh` for .htm attachments generation.

`collection.yml` is using in `collection.sh`:
```
bundle exec metanorma collection collection.yml -x xml,html,presentation -w iso10303-47
```

@opoudjis please confirm that `collection.sh`, `collection.yml` and `html_attachments.sh` are using in the metanorma files generation and we need them.

`schemas.yaml` is using in:
- `sections_common\04-schemas.adoc`
- `00-introduction.adoc`
- `94-expressg-diagrams.adoc`

Note: `collection.yml` and `schemas.yaml` are unique for each document.

**Comment by opoudjis** [comment]
If you want attachments in the collection, and rendered as HTML as well as TXT at that, you need something to generate them. We went through that concern three years ago.

If you want collections to be processed, you need collection manifests.

If you want documents to be processed and then converted into collections with attachments, you need a script to do so.

"shouldn't be there" is wrong and disruptive. No attachments and no collection manifests and no collection scripts simply means no processing of the documents. @Intelligent2013 was about to cease generating those files, and that would have left you with no output but a single monolithic web page per part. 

If you may have in mind some master process doing all those steps internal to stepmod2mn, and not generating config files, you should be architecting and communicating it. (What will actually happen is that stepmod2mn will ABSOLUTELY generate the config files, then run the compilation, and then delete the config files.) 

However, given that 

(a) I have spent a month and have only just got individual parts generating at all, 
(b) you want this all wrapped up by the end of the year, 
(c) you are now onboarding someone new who has not had anything to do with the process to date, and is therefore unfamiliar with what is needed in it,

I suggest that disrupting a process we have not even consolidated yet is a bad idea. I have not even been able to generate two collections in tandem yet, and I will *emphatically* need access to these config files to do so.

Revisit this issue in a couple of months, when we've established a workflow for generating parts and collections of parts of the document, and after I have explained to the developers involved how the collections are generated. Right now, "shouldn't be there" is getting in the way of me doing my job.

**Comment by HassanAkbar** [comment]
@ronaldtse As pointed out by @opoudjis we need the generated files, so I think we should not remove them for now, we can revisit this issue later.

**Pull request merged**
