### PR TITLE
removing CVS references

### PR DESCRIPTION
**Pull request by HassanAkbar**
- Support for CVS is removed

Fixes #121

### CODE REVIEW

**Comment by ronaldtse** [comment]
@HassanAkbar thanks! We do need to replace the CVS "reference_string" information with the corresponding Git commit hashes.

**Comment by HassanAkbar** [comment]
@ronaldtse Currently we were adding the `Working revision` and `Repository revision` from CVS for every single file, and then comparing them and adding a status (`up to date` or `differs`) for each file based on the comparison.
But Git is commit based and distributed so when should we state that file status is `differs`?
1. If the file is updated locally? OR a file is updated and committed locally?
2. If the file is updated on the main branch compared to current branch.
3. If the new changes are pushed by someone else on the same branch on Git?

Also Git have SHAs for each commit and not for each file. Should we add the SHA of the “latest commit to the branch” or “latest commit that have changes in that file” to reference_string?

**Comment by ronaldtse** [comment]
Actually you’re right. We only need to record a single Git commit hash for the whole document. We just need to add that in some file.

**Comment by HassanAkbar** [comment]
@ronaldtse Which SHA hash do we want to save in the `reference_string`?
1. The SHA of the latest commit that modified that file
2. The SHA of the current branch

**Comment by ronaldtse** [comment]
SHA of the current branch of the Git repository used to build the document.

**Comment by ronaldtse** [comment]
@TRThurman this change only applies to the ISO 10303-2 generation code, so it is only a downstream consumer of the new WG12-STEPMOD Git repository. It shouldn’t affect the repo itself.

**Review by ronaldtse — APPROVED** [review]
Thanks @HassanAkbar !

**Pull request merged**
