### PR TITLE
updated to not create empty changes files

### PR DESCRIPTION
**Pull request by HassanAkbar**
The issue is that changes files are being generated for all the schemas even if there are no changes for that type.
I have updated the code and now it no longer generates these files if they are empty.

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse In this PR, I've updated the code to stop the generation of empty change files. 

But as you mentioned here https://github.com/metanorma/stepmod-utils/issues/237#issuecomment-1928587499 that 
> This means there should ONLY be 6 arm_lf.changes.yaml and 4 mim_lf.changes.yaml files.

This will still not happen because of the files like below that only have general description, will created all four files (`arm.changes.yaml`, `mim.changes.yaml`, `arm_lf.changes.yaml`, `mim_lf.changes.yaml`) with same data.

```xml
<changes>
      <change version="2">
         <description> No ARM EXPRESS declarations and interface specifications have been added,
            removed or modified. Definition added for "Activity" and description of the
            "chosen_method" attribute of Activity clarified. </description>
           </change> 
       <change version="3">
        <description>
        Updated bibliography.
        </description>      
       </change>
   </changes>
```

The output for above changes will be 4 files (`arm.changes.yaml`, `mim.changes.yaml`, `arm_lf.changes.yaml`, `mim_lf.changes.yaml`) all with below output.

```yaml
---
schema: activity
change_edition:
- version: '2'
  description: No ARM EXPRESS declarations and interface specifications have been
    added, removed or modified. Definition added for "Activity" and description of
    the "chosen_method" attribute of Activity clarified.
- version: '3'
  description: Updated bibliography.

```

**Comment by TRThurman** [comment]
The arm, arm_lf, mim, mim_lf change clauses are contained in a <change version="N" xml element.
So the descriptions cited are not part of the arm, mim, arm_lf,mim_lf and should not generated corresponding yaml files.
There should be a change yaml file for the document itself.

**Comment by HassanAkbar** [comment]
@TRThurman @ronaldtse Just for confirmation, 
- `arm.changes.yaml`, `mim.changes.yaml`, `arm_lf.changes.yaml`, `mim_lf.changes.yaml` these files will ONLY be generated if there is a corresponding `<type.changes>` block in the xml i.e `<arm_longform.changes>` will create `arm_lf.changes.yaml` file.
- There will a separate file for description that is inside `<change version="N">` tag but outside of `<type.changes>` block. As currently there is no such file, what should we name this? Maybe `changes.yaml`?

**Comment by TRThurman** [comment]
See issue #237 for more details.

**Comment by ronaldtse** [comment]
> * There will a separate file for description that is inside `<change version="N">` tag but outside of `<type.changes>` block. As currently there is no such file, what should we name this? Maybe `changes.yaml`?

@HassanAkbar is this not implemented? I don't see those files.

**Comment by HassanAkbar** [comment]
@ronaldtse this has been implemented according to the specifications in https://github.com/metanorma/stepmod-utils/issues/237#issuecomment-1931506491

Here Is the count of all the files that are generated on `develop` branch of `iso-10303-stepmod-wg12` repo.

Screenshot 2024-02-10 at 5 37 20 PM

This is the structure of the `changes.yaml` file.

Screenshot 2024-02-10 at 5 34 44 PM

**Comment by TRThurman** [comment]
@HassanAkbar, glad to see this. How does this help us to properly build a document? I would have expected a test would be included to build a document.

**Comment by TRThurman** [comment]
@HassanAkbar, the information I provided above is incomplete. It only applies to module documents, e.g., ISO/TS 10303-1NNN.
Here is the relevant dtd for resource_docs
wg12-stepdev/dtd/res_doc/resource.dtd
The changes entry is found in resource_docs/<name>/resource.xml

**Comment by ronaldtse** [comment]
@HassanAkbar I can confirm that what you have is correct. 

I've added code so that we move the `changes.yaml` (document changes) file into the respective documents for those modules. (as those changes are ones like "updated bibliography" things that typically has nothing to do with the schema itself, although I can see some exceptions that are probably mistakes).

**Comment by ronaldtse** [comment]
> @HassanAkbar, the information I provided above is incomplete. It only applies to module documents, e.g., ISO/TS 10303-1NNN. Here is the relevant dtd for resource_docs wg12-stepdev/dtd/res_doc/resource.dtd The changes entry is found in resource_docs//resource.xml

Thanks @TRThurman , the resource changes were properly extracted, only the modules were problematic. Thanks!

**Pull request merged**
