### PR TITLE
migrating mapping_table to yaml files

### LINKED ISSUE #239: Migrate `module.xml` `<mapping_table>` to YAML file `mapping.yaml`
In every `module.xml`, there is a `<mapping_table>` element. We need to convert this into a `mapping.yaml` file (we already have `mapping.changes.yaml`, so let's keep it at the same place).

Let's use Shale to parse it according to the DTD (`module.dtd`).

This element looks like this:
```xml
  <mapping_table>
    <ae ...>
      ...
    </ae>
  </mapping_table>
```

Elements can look like:
```
      <!--  ++  AFFECTED_PLANE_TOLERANCE_ZONE  ++ -->
      <ae entity="Affected_plane_tolerance_zone" extensible="NO">
         <aimelt>tolerance_zone</aimelt>
         <source>ISO 10303-47</source>
         <aa attribute="affected_plane" assertion_to="Axis_placement_shape_element">
            <aimelt>PATH</aimelt>
            <refpath>
			tolerance_zone &lt;=
			shape_aspect &lt;-
			shape_aspect_relationship.relating_shape_aspect
			shape_aspect_relationship
			{shape_aspect_relationship.name = 'affected plane association'}
			shape_aspect_relationship.related_shape_aspect -&gt;
			shape_aspect
		</refpath>
         </aa>
      </ae>
```

```xml
      <!--  ++  ALL_AROUND_SHAPE_ELEMENT  ++ -->
      <ae entity="All_around_shape_element" extensible="NO">
         <aimelt>all_around_shape_aspect</aimelt>
         <source>ISO 10303-47</source>
      </ae>
```

```xml
      <!--  ++  TOLERANCE_ZONE  ++ -->
      <ae entity="Tolerance_zone" extensible="NO">
         <aimelt>tolerance_zone</aimelt>
         <source>ISO 10303-47</source>
         <aa attribute="form_type">
            <alt_map id="1">
               <description>If form_type has the value within_a_circle</description>
               <aimelt>tolerance_zone_form.name</aimelt>
               <refpath>{tolerance_zone_form.name = 'within a circle'}</refpath>
            </alt_map>
            <alt_map id="2">
               <description>If form_type has the value within_a_cylinder</description>
               <aimelt>tolerance_zone_form.name</aimelt>
               <refpath>{tolerance_zone_form.name = 'within a cylinder'}</refpath>
            </alt_map>
            <!-- ... -->
         </aa>
         <aa attribute="zone_for" assertion_to="Geometric_tolerance">
            <aimelt>PATH</aimelt>
            <refpath>tolerance_zone 
tolerance_zone.defining_tolerance[i] -&gt;
tolerance_zone_target = geometric_tolerance
geometric_tolerance
</refpath>
         </aa>
         <!-- ... -->
      </ae>
```

### PR DESCRIPTION
**Pull request by HassanAkbar**
Migrating `mapping_table` to `mapping.yaml` file.

The output of the `mapping.yaml` file is something like

```yaml
---
ae:
- entity: Activity
  aimelt:
    content: executed_action
  source:
    content: ISO 10303-41
  express_ref: []
  alt_map: []
  aa:
  - attribute: name
    aimelt:
      content: action.name
    source:
      content: ISO 10303-41
    express_ref: []
    refpath:
      content: "executed_action\n\t\t\t\t executed_action <= action\n\t\t\t\t action.name"
    alt_map: []
  - attribute: description
    aimelt:
      content: action.description
    source:
      content: ISO 10303-41
    express_ref: []
    refpath:
      content: "executed_action\n\t\t\t\t executed_action <= action\n\t\t\t\t action.description"
    alt_map: []
  - attribute: chosen_method
    assertion_to: Activity_method
    aimelt:
      content: PATH
    source: {}
    express_ref: []
    refpath:
      content: "executed_action\n\t\t\t\t executed_action <= action\n         action.chosen_method
        -> action_method\n         action_method\n       "
    alt_map: []
  - attribute: id
    aimelt:
      content: id_attribute.attribute_value
    source:
      content: ISO 10303-41
    express_ref: []
    refpath:
      content: "executed_action\n\t\t\t\t executed_action <= action\n\t\t\t\t action
        <- id_attribute.identified_item\n\t\t\t\t id_attribute.attribute_value"
    alt_map: []
- entity: Activity_relationship
  aimelt:
    content: action_relationship
  source:
    content: ISO 10303-41
  express_ref: []
  alt_map: []
  aa:
  - attribute: description
    aimelt:
      content: action_relationship.description
    source:
      content: ISO 10303-41
    express_ref: []
    alt_map: []
  - attribute: name
    aimelt:
      content: action_relationship.name
    source:
      content: ISO 10303-41
    express_ref: []
    alt_map: []
  - attribute: related_activity
    assertion_to: Activity
    aimelt:
      content: PATH
    source: {}
    express_ref: []
    refpath:
      content: "\n\t\t\t\t action_relationship\n         action_relationship.related_action
        -> action\n         action => executed_action\n       "
    alt_map: []
  - attribute: relating_activity
    assertion_to: Activity
    aimelt:
      content: PATH
    source: {}
    express_ref: []
    refpath:
      content: |-
        action_relationship
                 action_relationship.relating_action -> action
                 action => executed_action
    alt_map: []
- entity: Activity_status
  aimelt:
    content: action_status
  source:
    content: ISO 10303-41
  express_ref: []
  alt_map: []
  aa:
  - attribute: assigned_activity
    assertion_to: Activity
    aimelt:
      content: PATH
    source: {}
    express_ref: []
    refpath:
      content: "\n\t\t\t\t action_status\n\t\t\t\t action_status.assigned_action ->
        executed_action\n\t\t\t\t "
    alt_map: []
  - attribute: status
    aimelt:
      content: action_status.status
    source:
      content: ISO 10303-41
    express_ref: []
    alt_map: []
- entity: Applied_activity_assignment
  aimelt:
    content: applied_action_assignment
  source:
    content: ISO 10303-1047
  express_ref: []
  alt_map: []
  aa:
  - attribute: assigned_activity
    assertion_to: Activity
    aimelt:
      content: PATH
    source: {}
    express_ref: []
    refpath:
      content: "applied_action_assignment \n\t\t\t\t applied_action_assignment <=
        action_assignment\n\t\t\t\t action_assignment\n\t\t\t\t action_assignment.assigned_action
        -> action\n\t\t\t\t action => executed_action\n\t\t\t\t "
    alt_map: []
  - attribute: items
    assertion_to: activity_item
    aimelt:
      content: PATH
    source: {}
    express_ref: []
    refpath:
      content: "applied_action_assignment\n\t\t\t\t applied_action_assignment.items[i]
        -> action_items\n\t\t\t\t "
    alt_map: []
  - attribute: role
    aimelt:
      content: object_role.name
    source:
      content: ISO 10303-41
    express_ref: []
    refpath:
      content: "applied_action_assignment \n\t\t\t\t applied_action_assignment <=
        action_assignment\n\t\t\t\t action_assignment.role -> object_role\n\t\t\t\t
        object_role.name\n\t\t\t\t "
    alt_map: []
sc: []
```

closes #239

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse as shale depends on ruby `3.0`, if we want to use it then we will have to drop support for ruby `2.7` from `stepmod-utils`.

**Comment by TRThurman** [comment]
This approach will cause problems for mapping spec checkers.

> The information in the rendered HTML page for the mapping spec syntax is missing critical syntactical information. The design intent was that trailing symbols not otherwise enclosed by ']})' would have a newline following that symbol. Those trailing symbols are ( newline, =, =>, <=, ->, <- ).
> Because the XSLT doesn't enforce newline checking for those use cases, sloppy layout has crept in leading to inconsistent experience for the reader.
> The tabs are also not relevant.
> 

Can we capture this into an array so that post-processing checking software will have an easier time of it:

e.g., This:
refpath:
  content:
    - type: term
      value: "executed_action"
    - type: symbol
      value: "<="
    - type: term
      value: "action"
    - type: symbol
      value: "."
    - type: term
      value: "name"

instead of this:
refpath:
      content: "executed_action executed_action <= action action.name"

Of critical importance is to note that 
a- The array takes care of the linefeed issue
b- The symbols are actually encoded as symbols by the translation application.

The html generator will generate consistent output independent of the sloppy input.

**Comment by ronaldtse** [comment]
> @ronaldtse as shale depends on ruby `3.0`, if we want to use it then we will have to drop support for ruby `2.7` from `stepmod-utils`.

Let's drop Ruby 2.7. We don't need 2.7.

**Comment by ronaldtse** [comment]
@TRThurman I am very reluctant to start parsing the content of the mapping spec because it will take us a long time to finalize the grammar, the parser, etc before we can even get back to the document. Yes it will be cleaner and easier but we don't have resourcing to do that.

I suggest that this "mapping spec spec" project be taken at ELF properly and then things can develop from there. We are really running out of resources for this project...

**Comment by ronaldtse** [comment]
@TRThurman actually perhaps you're suggesting us to tokenize the actual mapping and just strip all whitespaces? If that's the case it's doable right @HassanAkbar ?

The source data looks like this (from `geometric_tolerance/module.xml`):
```xml
   <mapping_table>
      <!--  ++  AFFECTED_PLANE_TOLERANCE_ZONE  ++ -->
      <ae entity="Affected_plane_tolerance_zone" extensible="NO">
         <aimelt>tolerance_zone</aimelt>
         <source>ISO 10303-47</source>
         <aa attribute="affected_plane" assertion_to="Axis_placement_shape_element">
            <aimelt>PATH</aimelt>
            <refpath>
			tolerance_zone &lt;=
			shape_aspect &lt;-
			shape_aspect_relationship.relating_shape_aspect
			shape_aspect_relationship
			{shape_aspect_relationship.name = 'affected plane association'}
			shape_aspect_relationship.related_shape_aspect -&gt;
			shape_aspect
		</refpath>
         </aa>
      </ae>

```

**Comment by ronaldtse** [comment]
But we need to keep the "newlines" because they indicate a formatting we cannot recreate...

**Comment by TRThurman** [comment]
YesStrip the white space except for new lines On Apr 10, 2024, at 4:50 AM, Thomas Thurman ***@***.***> wrote:﻿YesKeep the new lines as they are part of the syntax.The tab characters aren’t.I am ok with doing this at ELF.Note that there are supposed to be new lines after (->, <-, =>, <=), but that is not enforced.On Apr 10, 2024, at 2:43 AM, Ronald Tse ***@***.***> wrote:﻿
But we need to keep the "newlines" because they indicate a formatting we cannot recreate...

**Comment by HassanAkbar** [comment]
> @TRThurman actually perhaps you're suggesting us to tokenize the actual mapping and just strip all whitespaces? If that's the case it's doable right @HassanAkbar ?
> 
> The source data looks like this (from `geometric_tolerance/module.xml`):
> 
> ```
>    <mapping_table>
>       
>       <ae entity="Affected_plane_tolerance_zone" extensible="NO">
>          <aimelt>tolerance_zone</aimelt>
>          <source>ISO 10303-47</source>
>          <aa attribute="affected_plane" assertion_to="Axis_placement_shape_element">
>             <aimelt>PATH</aimelt>
>             <refpath>
> 			tolerance_zone &lt;=
> 			shape_aspect &lt;-
> 			shape_aspect_relationship.relating_shape_aspect
> 			shape_aspect_relationship
> 			{shape_aspect_relationship.name = 'affected plane association'}
> 			shape_aspect_relationship.related_shape_aspect -&gt;
> 			shape_aspect
> 		</refpath>
>          </aa>
>       </ae>
> ```

@ronaldtse I'm confused by this statement, can you let me know what should be the expected output for the given input?

**Comment by ronaldtse** [comment]
We just want to strip the indents:
```xml
            <refpath>
			tolerance_zone &lt;=
			shape_aspect &lt;-
			shape_aspect_relationship.relating_shape_aspect
			shape_aspect_relationship
			{shape_aspect_relationship.name = 'affected plane association'}
			shape_aspect_relationship.related_shape_aspect -&gt;
			shape_aspect
		</refpath>
```

=>
```
tolerance_zone <=
shape_aspect <-
shape_aspect_relationship.relating_shape_aspect
shape_aspect_relationship
{shape_aspect_relationship.name = 'affected plane association'}
shape_aspect_relationship.related_shape_aspect ->
shape_aspect
```

**Comment by TRThurman** [comment]
This is input:
content: "applied_action_assignment \n\t\t\t\t applied_action_assignment <=
        action_assignment\n\t\t\t\t action_assignment.role -> object_role\n\t\t\t\t
        object_role.name\n\t\t\t\t "

What is output?

**Comment by ronaldtse** [comment]
> What is output?

This:
```
applied_action_assignment 
applied_action_assignment <= action_assignment
action_assignment.role -> object_role
object_role.name
```

**Comment by TRThurman** [comment]
What is the correct interpretation of this:

`content: |2`

or

`content: |`

**Comment by ronaldtse** [comment]
> @ronaldtse as shale depends on ruby `3.0`, if we want to use it then we will have to drop support for ruby `2.7` from `stepmod-utils`.

Ruby 2.7 is failing as the gem no longer supports it. 

We need to update the tests so it no longer tests against 2.7 if not supported. Ping @CAMOBAP .

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar !

**Comment by ronaldtse** [comment]
@HassanAkbar how does this functionality actually work? I am not seeing the `mapping.yaml` files generated at all.

**Comment by ronaldtse** [comment]
@HassanAkbar I got it working. Thanks!

**Pull request merged**
