### PR TITLE
feat: adding generate latex command

### PR DESCRIPTION
**Pull request by HassanAkbar**
Added `stepmod-generate-latex` command.

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
@HassanAkbar can you also help add to the README on how to use this command? Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse while generating `latex concepts` from `glossarists concepts` I encountered an issue that the `concepts-yaml` in `10303-2` repo are not standard `glossarist concepts` they contain some extra fields which are `part`, `schema` and `document `. 

Do we need to handle this? If yes then how do you suggest we should proceed with this?

What I think we can do is
1. Update glossarist to read extra keys in `yaml` files and save them and add them back to `yaml` when writing back.
2. Add a config in `glossarist` to specify the concept class to be used.

**Comment by ronaldtse** [comment]
@HassanAkbar thank you for raising this question.

The `part`, `schema`, `document` are extra information that we can need to keep attached to the concepts for ISO 10303-2. In the future we will also see other types of such "domain-specific attributes".

So there are two ways we can do in Glossarist:

1. Allowing subclassing (which is what we do now)
2. Allow Glossarist to handle these extension attributes. I think this is also reasonable and could work together with 1.

For example, we can group extension attributes under:

```yaml
---
designation: ...
extensions:
  - attribute_id: an_ID_that_describes_the_type_of_attribute
    name: name of attribute
    value: value of attribute
  - attribute_id: iso-10303-2-attribute-schema
    value: action_schema
```

**Comment by HassanAkbar** [comment]
@ronaldtse facing a `segmentation fault` for ruby `3.2.1` on MacOS. I think it is caused by the Expressir C libraries os, opened an issue there (https://github.com/lutaml/expressir/issues/129).

What do you suggest we do for now? Should we remove support for ruby `3.2` or wait for the issue to resolve?

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar for raising this.yea Ruby 3.2 compatibility out for now. We will need to fix Expressir later.

**Comment by ronaldtse** [comment]
@HassanAkbar can you please help make the following changes:
* Move the `stepmod-generate-latex` command into the Glossarist gem, e.g. `glossarist generate-latex [concept-set-dir]`, using Thor
* Update the README to directly use this new `glossarist` command to extract the concepts into LaTeX.

Thanks.

**Review by ronaldtse — CHANGES_REQUESTED** [review]
As stated.

**Comment by ronaldtse** [comment]
The request to move the latex generation functionality was originally raised here:
* https://github.com/metanorma/iso-10303-2/issues/130

```sh
$ glossarist export -f latex [concept-set-yaml-dir]
```

**Comment by HassanAkbar** [comment]
Added the command in `glossarist` in this PR https://github.com/glossarist/glossarist-ruby/pull/54 so, no need for this here.

**Pull request closed without merging**
